# Generated by Django 5.0 on 2024-04-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vendorcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('Event_detail', models.TextField(max_length=2000)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wed.district')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wed.vendorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Company_name', models.CharField(max_length=30)),
                ('package', models.IntegerField(null=True)),
                ('About', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
                ('password', models.CharField(max_length=30)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wed.district')),
                ('vendor_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wed.vendorcategory')),
            ],
        ),
    ]
