# Generated by Django 5.0 on 2024-04-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0004_alter_enquiry_event_detail_alter_vendors_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='vendor',
            new_name='Vendor',
        ),
    ]
