# Generated by Django 5.0 on 2024-04-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0005_rename_vendor_enquiry_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
