# Generated by Django 5.0 on 2024-04-16 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0006_rename_vendor_enquiry_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='About',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='package',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='vendor_category',
        ),
        migrations.AddField(
            model_name='vendors',
            name='phone_number',
            field=models.CharField(default='your number', max_length=20),
        ),
        migrations.CreateModel(
            name='vendorlisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('About', models.CharField(max_length=1000)),
                ('package', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('photo_1', models.ImageField(blank=True, upload_to='images')),
                ('photo_2', models.ImageField(blank=True, upload_to='images')),
                ('photo_3', models.ImageField(blank=True, upload_to='images')),
                ('photo_4', models.ImageField(blank=True, upload_to='images')),
                ('photo_5', models.ImageField(blank=True, upload_to='images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wed.vendorcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wed.vendors')),
            ],
        ),
    ]
