# Generated by Django 5.0 on 2024-04-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0007_remove_vendors_about_remove_vendors_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlisting',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wed.vendors'),
        ),
    ]
