# Generated by Django 5.0 on 2024-04-17 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0008_alter_vendorlisting_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlisting',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wed.district'),
        ),
    ]
