# Generated by Django 5.0 on 2024-04-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0010_remove_vendorlisting_photo_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlisting',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='vendorlisting',
            name='photo_1',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='vendorlisting',
            name='photo_2',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='vendorlisting',
            name='photo_3',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='vendorlisting',
            name='photo_4',
            field=models.ImageField(upload_to='image'),
        ),
    ]
