# Generated by Django 5.0 on 2024-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0011_alter_vendorlisting_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(default='your number', max_length=20),
        ),
    ]
