# Generated by Django 5.0 on 2024-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0012_alter_enquiry_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Event_date',
            field=models.CharField(default='your Event date', max_length=20),
        ),
    ]
