# Generated by Django 5.0 on 2024-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0013_enquiry_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Event_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Event_detail',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
