# Generated by Django 5.0 on 2024-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0014_alter_enquiry_event_date_alter_enquiry_event_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlisting',
            name='About',
            field=models.TextField(max_length=1000),
        ),
    ]
