# Generated by Django 5.0 on 2024-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0015_alter_vendorlisting_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
