# Generated by Django 5.0 on 2024-04-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0016_alter_vendors_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlisting',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='vendorlisting',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='vendorlisting',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='vendorlisting',
            name='photo_4',
        ),
    ]
